sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: z3XB4aILY182rFyCi4uvMTxt5NMy3Yk0oTD6zg38eH7cxTD5wXpmc2x895cI/nwvtkCzfKhQf4F2w0SvmqCvK5/3Fp4+Xp7psSpX+y+tQKn4YWU4yM5e/amqCvNKCWkPcjqwqj6M2Vj9J9thdYFodIFtdW8k5tgTWGh+xC1ohErN4kY6pHMs3r3NPzBacBdzjTbpuwQsf3QofWT2ueqzR7FBnb3cdmfqgEA+/zDW9Ax/KYsxQHtdI8SLiu6bBInAYHZUTWOpVXUtVxvQZ6uoFudjn8FXorx2sVoQpauDZUpO6sWvgrNgK0+7X+oUkphGZSxH0hO3UFbNaCIMhfdoFCimsFIlVVCUGDZkhMvlu9YyzngTR3IWzybWbKgRL8jPlLJFvAGY/EpTJAB2IxPwLkOmUuReOz3o9xev3SIQAUm7+ftTNiVSiyVLWJKrbs3K3wkCMXNwsz30Fj5xqwTFeWO1KdUSueH6r9s/EULMm1LbDMjuuvWfMzowFoBwidXUy0TF/wBt7TgRWiaJitfteBwahFX6uGVtfKRff1hmHRsItRJltEFESGjFjwvDZOs/MV0Kc08uTcQdw6vPYI7epiNGqIRtT8ArUWJv1692WFM6y6ihqLyaUxqRPfc63PNSVDeiw3gco3huoZyvICuwFbUGfM5xGXgvE/+buoaGhRA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Indiscretions-of-Archie_3756
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy